junit:
  stage: test
  script:
   - mvn -f ./team1-app/pom.xml -B clean test

generate_artifacts:
  stage: deploy
  script:
   - mvn -f ./team1-app/pom.xml -B clean site package
  artifacts:
    paths:
    - team1-app/target/team1*.jar
